apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-x3kc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-x3kc
    app.kubernetes.io/part-of: e2e-golang
  name: devfile-sample-go-basic-x3kc
  namespace: e2e-demos-oaof-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-go-basic-x3kc
    weight: null
status: {}
